## ADA_student_typecast_fixnum.rb
#
# this code snippet typecast fixnums to strings
#
##



student_id = [ 847106, 299239, 296710, 615043, 456626] # harding coding values generated by ADA_student_rand_number.rb

5.times do 
	break_id = student_id.shift # werks as desired
	break_id = break_id.to_s
	email_id = break_id[3..6]
	puts email_id
end