## ADA_student_acct_email.rb
#
# this snippet generates the email address for each student in the student array
#
##


# hard coding variables for testing purposes
student_names = ["Eileen The Crow", "Xena Warrior Princess", "Vicar Amelia"] # hard coding variables for testing purposes
student_id = [ 847106, 299239, 296710, 615043, 456626] # harding coding values generated by ADA_student_rand_number.rb

# intializes variables and hashes utilized by this snippet
email_suffix = "@adadevelopersacademy.org"
all_last_name = []
email_name = " " # empty string to set email name to
email_id = "^^^" # empty string to set email id number to
last_name = "*"  # variable for last name split from student_names
last_three = " " # variable for last 3 digits stripped from student id


5.times do # this loop breaks the student array up into the needed parts
	break_array = student_names.shift
	# puts first_initial # werks
	first_initial = break_array[0]
	# splits names off 
	all_last_name = break_array.split
	# pushes off last name with ruby method
	last_name = all_last_name.last
	# splits ids out of array
	break_id = student_id.shift

	break_id.to_s # mebe didn't work
	#puts break_id
	# attempting to pull last three numbrs off after type casting to string
	last_three = break_id.split(//).last(3).join
	puts last_three
	email_id = last_three
	puts email_id
	# puts all_last_name
	puts "#{first_initial}#{last_name}#{email_id}#{email_suffix}" #
end



#	5.times do # this loop splits the first word off the names
#		first_initial = break_array[0]
#		puts first_initial
#	end


