## ADA_student_acct_email.rb
#
# this snippet generates the email address for each student in the student array
#
##


# hard coding variables for testing purposes
student_names = ["Eileen The Crow", "Xena Warrior Princess", "Vicar Amelia"] # hard coding variables for testing purposes
student_id = [ 847106, 299239, 296710, 615043, 456626] # harding coding values generated by ADA_student_rand_number.rb

# initializes variables and hashes utilized by this snippet
email_suffix = "@adadevelopersacademy.org"
all_last_name = []
# email_name = " " # empty string to set email name to
email_id = " " # empty string to set email id number to
last_name = " "  # variable for last name split from student_names
student_email = []



5.times do # this loop breaks the student array up into the needed parts
# Student name and 1st initial
	# splits the student names out of the array
	break_array = student_names.shift

	# splits off first initial
	first_initial = break_array[0] # this line is triggering an error message, error triggered by poorly written test ilne 9 #
	# puts first_initial # print debuggin' werks

# splits last names off 
	all_last_name = break_array.split
	# puts all_last_name # print debuggin' werks

# pushes off last name with ruby method
	last_name = all_last_name.last

# slices id number out of array
	break_id = student_id.shift # werks as desired

# type cast fixnum to string
	break_id = break_id.to_s

# slices desired segment of id number (now string type)
	email_id = break_id[3..6]
	# puts email_id # print debuggin' werks
	
# generates student's email address
	email = "#{first_initial}#{last_name}#{email_id}#{email_suffix}" # puts email # print debuggin' werks
	
# places student emails into array
	student_email.push(email)
	# puts student_email # print debuggin' werks

end



#	5.times do # this loop splits the first word off the names
#		first_initial = break_array[0]
#		puts first_initial
#	end


